name: Xbox

on: [push, pull_request]

jobs:
  Xbox:
    runs-on: ubuntu-latest

    steps:
    - name: Install and Setup Dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y flex bison clang lld llvm

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Compile
      run: |
        eval $(lib/nxdk/bin/activate -s)
        cd lib/nxdk
        make NXDK_ONLY=y
        make tools
        cd ../..
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=lib/nxdk/share/toolchain-nxdk.cmake
        cmake --build .

    # Only create artifact on a push to xbox
    - if: github.event_name == 'push' 
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: XeniumTools
        path: |
          XeniumTools.iso
          XeniumTools
